title @s[scores={foton=0}] actionbar §l||||||||||||||||||||||||||||||§e
title @s[scores={foton=1}] actionbar §l|||||||||||||||||||||||||||||§e|
title @s[scores={foton=2}] actionbar §l||||||||||||||||||||||||||||§e||
title @s[scores={foton=3}] actionbar §l|||||||||||||||||||||||||||§e|||
title @s[scores={foton=4}] actionbar §l||||||||||||||||||||||||||§e||||
title @s[scores={foton=5}] actionbar §l|||||||||||||||||||||||||§e|||||
title @s[scores={foton=6}] actionbar §l||||||||||||||||||||||||§e||||||
title @s[scores={foton=7}] actionbar §l|||||||||||||||||||||||§e|||||||
title @s[scores={foton=8}] actionbar §l||||||||||||||||||||||§e||||||||
title @s[scores={foton=9}] actionbar §l|||||||||||||||||||||§e|||||||||
title @s[scores={foton=10}] actionbar §l||||||||||||||||||||§e||||||||||
title @s[scores={foton=11}] actionbar §l|||||||||||||||||||§e|||||||||||
title @s[scores={foton=12}] actionbar §l||||||||||||||||||§e||||||||||||
title @s[scores={foton=13}] actionbar §l|||||||||||||||||§e|||||||||||||
title @s[scores={foton=14}] actionbar §l||||||||||||||||§e||||||||||||||
title @s[scores={foton=15}] actionbar §l|||||||||||||||§e|||||||||||||||
title @s[scores={foton=16}] actionbar §l||||||||||||||§e||||||||||||||||
title @s[scores={foton=17}] actionbar §l|||||||||||||§e|||||||||||||||||
title @s[scores={foton=18}] actionbar §l||||||||||||§e||||||||||||||||||
title @s[scores={foton=19}] actionbar §l|||||||||||§e|||||||||||||||||||
title @s[scores={foton=20}] actionbar §l||||||||||§e||||||||||||||||||||
title @s[scores={foton=21}] actionbar §l|||||||||§e|||||||||||||||||||||
title @s[scores={foton=22}] actionbar §l||||||||§e||||||||||||||||||||||
title @s[scores={foton=23}] actionbar §l|||||||§e|||||||||||||||||||||||
title @s[scores={foton=24}] actionbar §l||||||§e||||||||||||||||||||||||
title @s[scores={foton=25}] actionbar §l|||||§e|||||||||||||||||||||||||
title @s[scores={foton=26}] actionbar §l||||§e||||||||||||||||||||||||||
title @s[scores={foton=27}] actionbar §l|||§e|||||||||||||||||||||||||||
title @s[scores={foton=28}] actionbar §l||§e||||||||||||||||||||||||||||
title @s[scores={foton=29}] actionbar §l|§e|||||||||||||||||||||||||||||
title @s[scores={foton=30}] actionbar §l§asneak + attack
